In [1]:
from pymatgen.ext.matproj import MPRester
import numpy as np
from pymatgen.core.lattice import Lattice
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.io.cif import CifWriter
from pprint import pprint
from pymatgen.core.operations import SymmOp
from IPython.display import Markdown,display

with MPRester("BmFlV0IoLySTXxcf") as m:
    
    #données du matériaux
    structure = m.get_structure_by_material_id("mp-672285")
    
    #téléchargement du fichier cif
    w = CifWriter(structure)
    w.write_file('mp-672285(2).cif')

    #rotation d'ordre 3
    r = SymmOp.from_xyz_string('-y,x-y,z')
    r2 = r.rotation_matrix
    
    #plan miroir
    m = SymmOp.from_xyz_string('x,x-y,z')
    m2 = m.rotation_matrix
    
    #translation
    t = SymmOp.from_xyz_string('x+0.33,y-0.33,z-0.33')
    t2 = t.rotation_matrix
    

In [9]:
print('la matrice de rotation est donnée par')
print(r2)
print('on va déplacer un atome de Carbone de (1,0,0.19) vers (0,1,0.19)')

la matrice de rotation est donnée par
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
on va déplacer un atome de carbone de (1,0,0.19) vers (0,1,0.19)


![](rotation2.PNG)

![](rotation.png)

In [3]:
print('la matrice du plan miroir est donnée par')
print(m2)
print('on va déplacer un atome de Cuivre de (1,0,0) vers (1,1,0)')
print('on effectue une coupe pour obtenir le plan ab pour obtenir l image a est rouge (haut-gauche) et b est vert(bas-droite)')

la matrice du plan miroir est donnée par
[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
on va déplacer un atome de Cuivre de (1,0,0) vers (1,1,0)
on effectue une coupe pour obtenir le plan ab pour obtenir l image a est rouge (haut-gauche) et b est vert(bas-droite)


![](miroir2.PNG)

![](miroir.png)

In [7]:
print('la matrice de translation est donnée par')
print(t2)
print('on va déplacer un atome d azote (0.33,0.67,0.78) vers (0.67,0.33,0.45)')

la matrice de translation est donnée par
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
on va déplacer un atome d azote (0.33,0.67,0.78) vers (0.67,0.33,0.45)


![](translation2.PNG)

![](translation.png)

![]('')